run:
  timeout: 3m
  skip-files: []
  skip-dirs: []

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 12
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  tagliatelle:
    case:
      rules:
        json: snake
  errcheck:
    enable-all: true
    exclude-functions:
      - os.Stdout.WriteString

linters:
  disable-all: true
  enable:
    - godox

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude: []
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
        - funlen
        - godot
